{{- if eq .Values.database.existingSecret "" -}}
apiVersion: v1
data:
  password: {{ required "A password for your database is required!" .Values.database.password | b64enc }}
{{- if .Values.database.root.password }}
  rootpassword: {{ .Values.database.root.password | b64enc }}
{{- end }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    helm.sh/chart: {{ include "fusionauth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "fusionauth.database.secretName" . }}
type: Opaque
{{- end -}}
{{- if and .Values.search.user (eq .Values.search.existingSecret "") }}
{{- if eq .Values.database.existingSecret "" }}
---
{{- end }}
apiVersion: v1
data:
  username: {{ .Values.search.user | b64enc }}
  password: {{ required "A password for your search user is required!" .Values.search.password | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    helm.sh/chart: {{ include "fusionauth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "fusionauth.search.secretName" . }}
type: Opaque
{{- end -}}
